# Generated by Django 5.2.4 on 2025-11-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_quantity_estimate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='freshness_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
